### ISSUE TITLE
Points do not register anymore

### ISSUE THREAD

**Issue by 37223** [greybax/MSEdgeSearchClicker#1]
Noticed this morning, site works fine, but points won't register anymore. 

Not sure if anything could be done at all.

**Comment by hallstudios** [comment]
+1, also found they are not registering anymore.  MS must be clamping down on their fraud detection systems.

**Comment by greybax** [comment]
probably they added domain to blacklist. Or just blocking any iframe calls to their bing.com. We can verify if somebody could run this tool on their web server and see if it works

**Comment by 37223** [comment]
> probably they added domain to blacklist. Or just blocking any iframe calls to their bing.com. We can verify if somebody could run this tool on their web server and see if it works

I don't think issue is related to domain blocking. As you no longer get any points for searching bing using simple "/search?q=TEXT" 

One reference I've found mentions "search.js line 85 for &form=QBIR" but that's beyond my knowledge

**Comment by greybax** [comment]
> One reference I've found mentions "search.js line 85 for &form=QBIR" but that's beyond my knowledge

It's their local issue and not related to the current tool. This tool uses iframe to request my domain to bing search. And on some of these stages, it's blocking counting points for MS Rewards program

**Comment by NoSubstitute** [comment]
@greybax - is the online demo updated with the 30s delay? It doesn't feel like it? Feels faster. So fast that it today doesn't register any points, apart from the first one or maybe two. Then it stops registering more points.

Super annoying that MS has implemented delays.

**Comment by NoSubstitute** [comment]
Perhaps it can be made a setting, or set random amount of seconds/minutes between searches, as it currently seems to be a long time needed before repeat searches are registered.

**Comment by greybax** [comment]
> Perhaps it can be made a setting, or set random amount of seconds/minutes between searches, as it currently seems to be a long time needed before repeat searches are registered.

Yep, I can a look deeper into it on Sunday

**Comment by 37223** [comment]
I won't worry too much about it. I have a a feeling that this program is coming to an end.  Just today they banned whole bunch accounts for nothing. So it will be waste of time

**Comment by NoSubstitute** [comment]
I've noticed that if I type really long search phrases, more than 80 characters, but preferrably more than 100 characters, each search is registering, even when entering them immediately after each other.

**Comment by greybax** [comment]
@NoSubstitute I've deployed a new version with the following updates:
1. for each search make the length of string not less than 100 symbols
2. different time search requests in range of 15k - 35k ms

Browsers searches are counted now

**Comment by anythingplease** [comment]
I just tried it. Left it for about 10 minutes and only the first search counted. No mobile searches counted at all.

Tried re-opening it a few times after some delays and nothing counting either.

**Comment by greybax** [comment]
@anythingplease I've twinked a bit with parameters and browser searches are counted now at least on my end. 😄
~~Mobile version doesn't work and it's a known issue (working on it..)~~

**EDIT:** Mobile version works as well.

**Comment by anythingplease** [comment]
Just tried both and they are indeed working now! Awesome work as usual, thanks mate.

**Comment by NoSubstitute** [comment]
Oh, so it's possible to F12 the demo desktop version into thinking it's running on a mobile?

**Comment by greybax** [comment]
@NoSubstitute yes, but in my case it doesn't count if you do it simultaneously. If you do browser first, then mobile simulator then it works

**Comment by anythingplease** [comment]
Worked once or twice today then not anymore. I've noticed that clearing cookies from bing.com will sometimes allow it to work again but blocking all cookies from there doesn't work.

I don't know what changed in 2 days unless they are actively trying to prevent it from working.

**Comment by greybax** [comment]
@anythingplease I use Chrome and it still works on my end

**Comment by NoSubstitute** [comment]
Mobile simulation is "broken" again. Your code works great, but it's just not registering points.
Manual searches in DevTools simulation mode also doesn't work.

On a positive note, doing manual searches on a real phone with the simple 1, 12, 123, 1234n syntax works again, and consistently registers 7/10 searches.

**Comment by anythingplease** [comment]
Noticed this also, it's all a bit of a mess at the moment. I leave normal
clicker open all day and I get about half of the available points. Oh well,
it's better than nothing.

**Comment by greybax** [comment]
For browser search, I've noticed that they register clicks by 20 and need some delay to register other ones. The interval is about 5 mins

**Comment by redguyig** [comment]
> Mobile simulation is "broken" again. Your code works great, but it's just not registering points. Manual searches in DevTools simulation mode also doesn't work.
> 
> On a positive note, doing manual searches on a real phone with the simple 1, 12, 123, 1234n syntax works again, and consistently registers 7/10 searches.

uhh can you tell me more about the syntax on mobile like I quite didn't understand what you said there also yeah it isn't registering points for some reason.

**Comment by NoSubstitute** [comment]
Just type a 1, Enter, then after it loads, type a 2, Enter, load, type a 3, and so on and so on.

**Comment by NoSubstitute** [comment]
This works great on PC now, very stable.

But it doesn't seem to work at all on mobile.
It doesn't respect the time delay, so it refreshes very fast.
So fast that I can't make sure that the browser is properly logged into my account.

As soon as I start messing in the tiny frame, it refreshes, and kicks me out of the frame.

I can only see it long enough to verify that I am definitely not logged in, and therefore no searches are registering.
